// Demo data: departments, one user per role, faculty with different situations, a previous block
// (with carry-forward), and sample claims sitting at every stage of the approval chain.
require('dotenv').config();
const bcrypt = require('bcryptjs');
const PDFDocument = require('pdfkit');
const { pool, tx } = require('../src/db');
const { getSettings, fyOf, blockLabel, todayStr } = require('../src/rules');
const ledger = require('../src/services/ledger');
const claims = require('../src/services/claims');

const PASSWORD = 'Demo@1234';
const dayOffset = (n) => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10); };

function samplePdf(text) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ size: 'A5', margin: 30 });
    const bufs = [];
    doc.on('data', (b) => bufs.push(b));
    doc.on('end', () => resolve(Buffer.concat(bufs)));
    doc.fontSize(16).text('SAMPLE BILL (demo data)', { align: 'center' }).moveDown();
    doc.fontSize(11).text(text).moveDown().text('This is a placeholder bill generated by the seed script.');
    doc.end();
  });
}

async function seed() {
  const hash = await bcrypt.hash(PASSWORD, 10);
  const curFy = fyOf(todayStr());

  // ---- departments
  const dept = {};
  for (const [code, name] of [['CSE', 'Computer Science & Engineering'], ['EE', 'Electrical Engineering'], ['ME', 'Mechanical Engineering']]) {
    dept[code] = (await pool.query('INSERT INTO departments(code,name) VALUES ($1,$2) RETURNING id', [code, name])).rows[0].id;
  }

  // ---- users (all demo accounts share the same password)
  const midJoinYear = Math.min(Math.floor((curFy - 2021) / 3) * 3 + 2021 + 1, curFy);
  const U = [
    ['admin', 'System Administrator', 'ADM001', 'ADMIN', null, 'Administrator'],
    ['ar', 'Accounts Officer (AR)', 'ACC001', 'ACCOUNTS_AR', null, 'Assistant Registrar (Accounts)'],
    ['junior1', 'Accounts Staff One', 'ACC002', 'ACCOUNTS_JUNIOR', null, 'Junior Accountant'],
    ['junior2', 'Accounts Staff Two', 'ACC003', 'ACCOUNTS_JUNIOR', null, 'Junior Accountant'],
    ['registrar', 'Registrar (Demo)', 'REG001', 'REGISTRAR', null, 'Registrar'],
    ['dean', 'Dean FAA (Demo)', 'DEA001', 'DEAN_FAA', null, 'Dean, Faculty Affairs & Administration'],
    ['director', 'Director (Demo)', 'DIR001', 'DIRECTOR', null, 'Director'],
    ['hod.cse', 'Dr. Rahul Verma', 'F1001', 'HOD', 'CSE', 'Professor & HoD', { doj: '2009-07-01' }],
    ['hod.ee', 'Dr. Suresh Nair', 'F1002', 'HOD', 'EE', 'Professor & HoD', { doj: '2008-01-10' }],
    ['hod.me', 'Dr. Pooja Malhotra', 'F1003', 'HOD', 'ME', 'Professor & HoD', { doj: '2010-08-16' }],
    ['anita.sharma', 'Dr. Anita Sharma', 'F2001', 'FACULTY', 'CSE', 'Associate Professor', { doj: '2014-07-01' }],
    ['rohan.mehta', 'Dr. Rohan Mehta', 'F2002', 'FACULTY', 'CSE', 'Assistant Professor', { doj: `${midJoinYear}-06-15` }],
    ['kavya.rao', 'Dr. Kavya Rao', 'F2003', 'FACULTY', 'EE', 'Assistant Professor', { doj: '2017-12-04' }],
    ['arjun.singh', 'Dr. Arjun Singh', 'F2004', 'FACULTY', 'EE', 'Professor', { doj: '2012-01-02' }],
    ['nisha.kapoor', 'Dr. Nisha Kapoor', 'F2005', 'FACULTY', 'ME', 'Associate Professor', { doj: '2015-07-20' }],
    ['vikram.das', 'Dr. Vikram Das', 'F2006', 'FACULTY', 'ME', 'Professor (retiring this year)', { doj: '1996-08-01', dor: `${curFy}-11-30`, exit_type: 'RETIRE' }],
    ['sanjay.gupta', 'Dr. Sanjay Gupta', 'F2007', 'FACULTY', 'EE', 'Assistant Professor (on long leave)', { doj: '2018-07-02', on_leave_over_30: true }],
  ];
  const user = {};
  for (const [key, name, emp, role, d, desig, x = {}] of U) {
    const { rows } = await pool.query(
      `INSERT INTO users(name,email,emp_code,role,department_id,designation,doj,dor,exit_type,on_leave_over_30,password_hash)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,
      [name, `${key}@iitrpr.demo`, emp, role, d ? dept[d] : null, desig, x.doj || null, x.dor || null, x.exit_type || null, !!x.on_leave_over_30, hash]);
    user[key] = { ...rows[0], dept_code: d, dept_name: d };
  }

  // ---- blocks: previous (history), active (contains today), next
  const activeStart = Math.floor((curFy - 2021) / 3) * 3 + 2021;
  const blk = {};
  for (const s of [activeStart - 3, activeStart, activeStart + 3]) {
    blk[s] = (await pool.query('INSERT INTO cpda_blocks(start_fy,end_fy,label,active) VALUES ($1,$2,$3,$4) RETURNING *', [s, s + 2, blockLabel(s, s + 2), s === activeStart])).rows[0];
  }
  const prev = blk[activeStart - 3];
  const active = blk[activeStart];
  const settings = await getSettings();

  await tx(async (c) => {
    await ledger.initBlockAccounts(c, prev, settings, user.admin.id);
    // history migrated from the old manual register
    const spend = { 'anita.sharma': [120000, 'CONFERENCE'], 'arjun.singh': [210000, 'CONFERENCE'], 'nisha.kapoor': [60000, 'CONTINGENCY'], 'hod.cse': [90000, 'CONFERENCE'], 'hod.ee': [150000, 'CONFERENCE'], 'hod.me': [30000, 'CONTINGENCY'] };
    for (const [k, [amt, bucket]] of Object.entries(spend)) {
      const a = (await c.query('SELECT id FROM cpda_accounts WHERE user_id=$1 AND block_id=$2', [user[k].id, prev.id])).rows[0];
      if (a && amt) await ledger.addEntry(c, { account_id: a.id, fy: prev.start_fy + 1, type: 'EXPENDITURE', bucket, amount: amt, particulars: 'Expenditure migrated from manual CPDA register', created_by: user.admin.id });
    }
    // one account carried in more than the cap, to show the carry-forward limit
    const n = (await c.query('SELECT id FROM cpda_accounts WHERE user_id=$1 AND block_id=$2', [user['nisha.kapoor'].id, prev.id])).rows[0];
    if (n) await ledger.addEntry(c, { account_id: n.id, fy: prev.start_fy, type: 'CARRY_IN', amount: 150000, particulars: 'Carry-forward from earlier block (migrated)', created_by: user.admin.id });
    await ledger.initBlockAccounts(c, active, settings, user.admin.id);
    await ledger.carryForward(c, prev, active, settings, user.admin.id);
  });

  // ---- sample claims at each stage
  const bill = async (u, id, text) => {
    const buf = await samplePdf(text);
    await claims.addAttachment(u, id, { originalname: 'bill.pdf', mimetype: 'application/pdf', buffer: buf, size: buf.length });
  };
  const make = async (u, payload, { submit = true, special } = {}) => {
    const id = await claims.createOrUpdate(u, payload);
    await bill(u, id, `${payload.title}\nTotal: Rs ${payload.items.reduce((s, i) => s + i.amount, 0)}`);
    if (submit) await claims.submit(u, id, special || {});
    return id;
  };
  const item = (category, party, no, dOff, amount, remarks) => ({ category, party, invoice_no: no, invoice_date: dayOffset(dOff), amount, remarks });
  const approve = (u, id, extra = {}) => claims.act(u, id, { action: 'approve', ...extra });
  const reg = (page, sr, head, passed) => ({ register: { register_page: page, register_sr: sr, budget_head: head, amount_passed: passed } });
  const ar = user.ar, j1 = user.junior1;

  // A. fully approved and paid: international conference
  let id = await make(user['anita.sharma'], {
    kind: 'CONFERENCE', title: 'ICSE conference - paper presentation', event_name: 'International Conference on Software Engineering', event_location: 'Lisbon, Portugal',
    event_type: 'International', event_start: dayOffset(-20), event_end: dayOffset(-15), prior_approval_ref: 'DEAN/FAA/2026/118', attended: true, pay_to: 'FACULTY',
    items: [item('Registration Fee', 'ICSE organisers', 'REG-5521', -25, 42000), item('Travel (TA/DA)', 'Air ticket - economy', 'TKT-88312', -30, 58000)],
  });
  await approve(user['hod.cse'], id); await approve(ar, id, { assignee_id: j1.id });
  await approve(j1, id, reg('41', '212', 'CPDA - Conference', 100000)); await approve(ar, id);
  await approve(user.registrar, id); await approve(user.dean, id); await approve(user.director, id);
  await claims.markPaid(ar, id, 'NEFT-2026-0457');

  // B. waiting for HoD
  await make(user['anita.sharma'], { kind: 'CONTINGENT', title: 'Lab consumables and reference books', pay_to: 'VENDOR', items: [item('Consumables (research)', 'Sigma Scientific', 'INV-2290', -6, 12500), item('Books & Stationery', 'Book Corner', 'BC-771', -5, 6000)] });

  // C. waiting for Accounts AR to assign
  id = await make(user['rohan.mehta'], { kind: 'CONTINGENT', title: 'Professional body memberships', pay_to: 'FACULTY', items: [item('Membership Fees', 'IEEE', 'IEEE-33901', -8, 5400), item('Membership Fees', 'ACM', 'ACM-77120', -8, 4400)] });
  await approve(user['hod.cse'], id);

  // D. assigned to junior staff for register entry
  id = await make(user['kavya.rao'], { kind: 'CONTINGENT', title: 'Computer accessories for the lab', pay_to: 'VENDOR', items: [item('Computer Consumables', 'Digital Hub', 'DH-4412', -4, 8400), item('Repair & Maintenance of Computer', 'Tech Care', 'TC-120', -4, 4000)] });
  await approve(user['hod.ee'], id); await approve(ar, id, { assignee_id: j1.id });

  // E. waiting for Dean FAA
  id = await make(user['arjun.singh'], {
    kind: 'CONFERENCE', title: 'CODS-COMAD workshop', event_name: 'CODS-COMAD 2026', event_location: 'Hyderabad', event_type: 'National',
    event_start: dayOffset(-14), event_end: dayOffset(-12), prior_approval_ref: 'DEAN/FAA/2026/131', attended: true, pay_to: 'FACULTY',
    items: [item('Registration Fee', 'CODS-COMAD', 'CC-901', -16, 12000), item('Travel (TA/DA)', 'Rail ticket 2AC', 'PNR-44012', -15, 20000)],
  });
  await approve(user['hod.ee'], id); await approve(ar, id, { assignee_id: user.junior2.id });
  await approve(user.junior2, id, reg('42', '219', 'CPDA - Conference', 32000)); await approve(ar, id); await approve(user.registrar, id);

  // F. rejected by Registrar
  id = await make(user['nisha.kapoor'], { kind: 'CONTINGENT', title: 'Journal publication charges', pay_to: 'FACULTY', items: [item('Publication Charges', 'Open Access Journal', 'OA-2231', -7, 24000)] });
  await approve(user['hod.me'], id); await approve(ar, id, { assignee_id: j1.id }); await approve(j1, id, reg('42', '220', 'CPDA - Contingency', 24000)); await approve(ar, id);
  await claims.act(user.registrar, id, { action: 'reject', comment: 'Journal is not on the approved list; resubmit with a different journal.' });

  // G. draft
  await make(user['vikram.das'], { kind: 'CONTINGENT', title: 'Printer cartridges', pay_to: 'FACULTY', items: [item('Computer Consumables', 'Office Mart', 'OM-9921', -2, 7600)] }, { submit: false });

  // H. late claim with special approval request (waiting at HoD)
  await make(user['kavya.rao'], {
    kind: 'CONFERENCE', title: 'Workshop on power electronics', event_name: 'Power Electronics Workshop', event_location: 'IIT Delhi', event_type: 'National',
    event_start: dayOffset(-52), event_end: dayOffset(-50), prior_approval_ref: 'DEAN/FAA/2026/090', attended: true, pay_to: 'FACULTY',
    items: [item('Registration Fee', 'IIT Delhi', 'PEW-118', -55, 6000), item('Travel (TA/DA)', 'Bus + local', 'BUS-221', -52, 4500)],
  }, { special: { special_request: true, special_reason: 'Reimbursement file was delayed because the organisers issued the receipt late.' } });

  // I. returned by HoD for correction
  id = await make(user['arjun.singh'], { kind: 'CONTINGENT', title: 'Subscription renewal', pay_to: 'FACULTY', items: [item('Subscription', 'Tech Journals Ltd', 'TJ-5521', -3, 9500)] });
  await claims.act(user['hod.ee'], id, { action: 'return', comment: 'Please attach the GST invoice, only the proforma is attached.' });

  console.log('Demo data loaded. All demo logins use the password:', PASSWORD);
}

module.exports = { seed };

if (require.main === module) {
  seed().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
}
